config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'static_pages#index'
  resources :users, only: :show
  resources :trips do
    resources :point_of_interests, only: [:create, :show, :edit, :update, :destroy]
  end

end

app/models/point_of_interest.rb
class PointOfInterest < ActiveRecord::Base
  belongs_to :trip
  belongs_to :user
  geocoded_by :address

  def address
    [street, city, state, zipcode].compact.join(', ')
  end

  after_validation :geocode
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  has_many :point_of_interests
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :trips
  has_many :point_of_interests
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/point_of_interests_controller.rb
class PointOfInterestsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :edit, :update, :destroy]

  def show
    @point_of_interest = PointOfInterest.find(params[:id])
  end

  def create
    @trip = Trip.find(params[:trip_id])
    @trip.point_of_interests.create(point_of_interest_params.merge(user: current_user))
    redirect_to trip_path(@trip)
  end

  def edit
    @trip = Trip.find(params[:trip_id])
    @point_of_interest = PointOfInterest.find(params[:id])
    if @point_of_interest.user != current_user
      render text: "Not Allowed", status: :unauthorized
    end
  end

  def update
    @point_of_interest = PointOfInterest.find(params[:id])
    if @point_of_interest.user != current_user
      render text: "Not Allowed", status: :forbidden
    end

    @point_of_interest.update_attributes(point_of_interest_params)
    if @point_of_interest.valid?
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @point_of_interest = PointOfInterest.find(params[:id])
    if @point_of_interest.user != current_user
      render text: "Not Allowed", status: :forbidden
    end

    @point_of_interest.destroy
    redirect_to root_path
  end

  private

  def point_of_interest_params
    params.require(:point_of_interest).permit(:name, :street, :city, :state, :zipcode)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index

  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :authenticate_user!

  def index
    @trips = Trip.all
  end

  def show
    @trip = Trip.find(params[:id])
    @point_of_interest = PointOfInterest.new
  end

  def new
    @trip = Trip.new
  end

  def create
    @trip = current_user.trips.create(trip_params)
    if @trip.valid?
      redirect_to trip_path(@trip)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def trip_params
    params.require(:trip).permit(:name)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @trips = Trip.all
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/point_of_interests_helper.rb
module PointOfInterestsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SpotHop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'SpotHop', root_path, class: 'navbar-brand' %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to 'New Trip', new_trip_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        </ul>
        <form class="navbar-form navbar-left">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to 'My Profile', user_path(current_user) %></li>
            <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to 'Sign in', new_user_session_path %></li>
            <li><%= link_to 'Sign up', new_user_registration_path %></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <% if notice.present? %>
    <p class="alert alert-info"><%= notice %></p>
  <% end %>
  <% if alert.present? %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

<%= yield %>

</body>
</html>

app/views/point_of_interests/show.html.erb
<h1><%= @point_of_interest.name %></h1>

<div>

  <% if @point_of_interest.latitude.present? && @point_of_interest.longitude.present? %>
    <script>

      function initMap() {
        var myLatLng = {lat: <%= @point_of_interest.latitude %>, lng: <%= @point_of_interest.longitude %>};

        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 15,
          center: myLatLng
        });

        var marker = new google.maps.Marker({
          position: myLatLng,
          map: map,
          title: 'Hello World!'
        });
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAkdfe0mdBnUGL1EsCHte8Rsub6POEAaPQ&callback=initMap">
    </script>

    <div id="map"></div>
<% end %>

  <div class="pull-right">
    <% if current_user && current_user == @point_of_interest.user %>
      <%= link_to 'Edit', edit_trip_point_of_interest_path(:trip_id, @point_of_interest), class: 'btn btn-primary' %>
      <%= link_to 'Destroy', trip_point_of_interest_path, method: :delete, data: {confirm: 'Are you sure you want to delete this?'},class: 'btn btn-danger' %>
    <% end %>
  </div>
</div>

app/views/static_pages/index.html.erb
<h1>Welcome</h1>

app/views/trips/index.html.erb
<h1>List of Trips</h1>

app/views/trips/new.html.erb
<h1>New Trip</h1>
<br><br>
<div class="spot-box col-xs-10 col-xs-offset-1">
  <%= form_for @trip do |f| %>
    <%= f.label :name %><br>
    <%= f.text_field :name %><br><br>
    <%= f.submit "Create", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/trips/show.html.erb
<h1>Trip Details</h1>

<h1><%= @trip.name %></h1>

<% @trip.point_of_interests.each do |poi| %>
  <% if poi.present? %>
    <div class="spot-box col-xs-10 col-xs-offset-1">
      <h3><%= link_to poi.name, trip_point_of_interest_path(@trip, poi) %></h3>
      <p>
        <%= poi.street %><br>
        <%= poi.city %><br>
        <%= poi.state %><br>
        <%= poi.zipcode %>
      </p>
    </div>
  <% end %>
<% end %>



<!-- Button trigger modal -->
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  Add a new Spot
</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">Add a new Spot</h4>
      </div>
      <%= form_for @point_of_interest, url: trip_point_of_interests_path(@trip) do |f| %>
      <div class="modal-body">
        <%= f.label :name %>
        <%= f.text_field :name %>
        <%= f.label :street %>
        <%= f.text_field :street %>
        <%= f.label :city %>
        <%= f.text_field :city %>
        <%= f.label :state %>
        <%= f.text_field :state %>
        <%= f.label :zipcode %>
        <%= f.text_field :zipcode %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= f.submit "Create", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h1><%= @user.email %></h1>

<% @trips.each do |trip| %>
  <h3><%= link_to trip.name, trip_path(trip) %></h3>
<% end %>